version: 2
jobs:
  build:
    docker:
      - image: lomereiter/sm-webapp:0.6.1.1

      - image: postgres:9.5-alpine
        environment:
          POSTGRES_USER: sm
          POSTGRES_PASSWORD: password

      - image: elasticsearch:5.4.0-alpine
        environment:
          ES_JAVA_OPTS: "-Xms512m -Xmx512m"
        command: [elasticsearch, -Etransport.host=127.0.0.1]

      - image: redis:3.2-alpine

      - image: rabbitmq:3.6-alpine
        environment:
          RABBITMQ_DEFAULT_USER: sm
          RABBITMQ_DEFAULT_PASS: password

    working_directory: /tmp/webapp
    steps:
      - checkout
      - restore_cache:
          keys:
            - yarn-cache-{{ .Branch }}-{{checksum "yarn.lock"}}
      - run:
          name: Install node packages
          command: |
            yarn global add yarn
            yarn install
            npm rebuild node-sass  # https://github.com/sass/node-sass/issues/1804
            cp tests/e2e/conf.js conf.js
            cp tests/e2e/clientConfig.json src/
            yarn run build-ci
      - save_cache:
          key: yarn-cache-{{ .Branch }}-{{checksum "yarn.lock"}}
          paths:
            - /usr/local/share/.cache/yarn
      - run:
          name: Start GraphQL server and service mocks
          command: |
            rm -rf sm-graphql
            git clone https://github.com/metaspace2020/sm-graphql --branch rel-v0.7
            export NPM_CONFIG_LOGLEVEL=warn
            cd sm-graphql && npm install && cd ..
            cp sm-graphql/tests/mock_config.js sm-graphql/config/default.js
            forever start sm-graphql/tests/api_mocks.js
            cd sm-graphql && forever start server.js
      - run:
          name: Load test data into the database and ElasticSearch
          command: |
            cd .circleci && bash populate_pg_es.sh
      - run:
          name: Run tests
          command: |
            export NPM_CONFIG_LOGLEVEL=warn
            Xvfb :99 -screen 0 1280x1024x24 &
            #while true; do echo '---'; sleep 5; done   # uncomment this line for debugging
            export DISPLAY=:99
            stty cols 80  # https://github.com/DevExpress/testcafe/issues/1469
            testcafe firefox tests/e2e/annotations.js --app "yarn run dev" --no-color --app-init-delay=10000
